addons:
  apt:
    packages:
      - xvfb

jdk: oraclejdk8

sudo: false # faster builds

install:
  - mvn install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
 - mvn test
 - mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
